"""alter type fase column in  Ranking table

Revision ID: 006b002d9f15
Revises: 58d6e3c67398
Create Date: 2024-04-07 14:27:52.789308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '006b002d9f15'
down_revision: Union[str, None] = '58d6e3c67398'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Ranking', sa.Column('fase', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Ranking', 'fase')
    # ### end Alembic commands ###
