"""create Ranking table

Revision ID: 0b665db99efa
Revises: e973e1df5229
Create Date: 2024-04-06 22:59:18.952931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b665db99efa'
down_revision: Union[str, None] = 'e973e1df5229'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Ranking',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('apelido', sa.String(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('sexo', sa.String(), nullable=True),
    sa.Column('categoria', sa.String(), nullable=False),
    sa.Column('id_competidor', sa.UUID(), nullable=False),
    sa.Column('total_jogo', sa.Float(), nullable=False),
    sa.Column('total_competidor', sa.Float(), nullable=False),
    sa.Column('nota_total', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('apelido'),
    sa.UniqueConstraint('categoria')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Ranking')
    # ### end Alembic commands ###
