"""add jogo_order column

Revision ID: 0c0705ec8b3d
Revises: 37139c54586a
Create Date: 2024-04-18 18:02:11.527035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c0705ec8b3d'
down_revision: Union[str, None] = '37139c54586a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Jogos', sa.Column('jogo_order', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Jogos', 'jogo_order')
    # ### end Alembic commands ###
