"""update models

Revision ID: 28c74aba19ee
Revises: 917b7c480219
Create Date: 2024-03-17 17:28:54.046738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28c74aba19ee'
down_revision: Union[str, None] = '917b7c480219'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Pontuacoes', sa.Column('id_competidor_1', sa.UUID(), nullable=True))
    op.add_column('Pontuacoes', sa.Column('id_competidor_2', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'Pontuacoes', 'Jogos', ['id_competidor_1'], ['id_competidor_1'], ondelete='CASCADE')
    op.create_foreign_key(None, 'Pontuacoes', 'Jogos', ['id_competidor_2'], ['id_competidor_2'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Pontuacoes', type_='foreignkey')
    op.drop_constraint(None, 'Pontuacoes', type_='foreignkey')
    op.drop_column('Pontuacoes', 'id_competidor_2')
    op.drop_column('Pontuacoes', 'id_competidor_1')
    # ### end Alembic commands ###
