"""u remove jogo_id column

Revision ID: 37139c54586a
Revises: f856652bc44e
Create Date: 2024-04-18 17:48:24.146482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37139c54586a'
down_revision: Union[str, None] = 'f856652bc44e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Jogos', 'jogo_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Jogos', sa.Column('jogo_id', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
