"""update models

Revision ID: 917b7c480219
Revises: b383f2ad19b3
Create Date: 2024-03-17 15:13:56.547051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '917b7c480219'
down_revision: Union[str, None] = 'b383f2ad19b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Jurados')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Jurados',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('nome', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='Jurados_pkey'),
    sa.UniqueConstraint('nome', name='Jurados_nome_key')
    )
    # ### end Alembic commands ###
