"""add relationship users in pontuacoes table

Revision ID: b383f2ad19b3
Revises: 363a53105f41
Create Date: 2024-02-17 05:25:32.864043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b383f2ad19b3'
down_revision: Union[str, None] = '363a53105f41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Pontuacoes', sa.Column('id_user', sa.UUID(), nullable=True))
    op.drop_constraint('Pontuacoes_id_jurado_fkey', 'Pontuacoes', type_='foreignkey')
    op.create_foreign_key(None, 'Pontuacoes', 'Users', ['id_user'], ['id'], ondelete='CASCADE')
    op.drop_column('Pontuacoes', 'id_jurado')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Pontuacoes', sa.Column('id_jurado', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'Pontuacoes', type_='foreignkey')
    op.create_foreign_key('Pontuacoes_id_jurado_fkey', 'Pontuacoes', 'Jurados', ['id_jurado'], ['id'], ondelete='CASCADE')
    op.drop_column('Pontuacoes', 'id_user')
    # ### end Alembic commands ###
