"""update Pontuacoes table

Revision ID: e973e1df5229
Revises: e9a47f67f8a5
Create Date: 2024-04-06 20:28:11.389558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e973e1df5229'
down_revision: Union[str, None] = 'e9a47f67f8a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Pontuacoes', sa.Column('jogo_valido', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Pontuacoes', 'jogo_valido')
    # ### end Alembic commands ###
