"""update Jogos table

Revision ID: e9a47f67f8a5
Revises: 917b7c480219
Create Date: 2024-04-06 16:51:10.263556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9a47f67f8a5'
down_revision: Union[str, None] = '917b7c480219'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Jogos', sa.Column('fase', sa.Integer(), nullable=False))
    op.drop_column('Jogos', 'jogo_valido')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Jogos', sa.Column('jogo_valido', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('Jogos', 'fase')
    # ### end Alembic commands ###
